### DEVO Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 96
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 13

# threshold for keyframe removal
KEYFRAME_THRESH: 15.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: True

# Select between random, gradient, scorer
PATCH_SELECTOR: 'scorer'
# Normalizer (only evs): none, rescale, standard (std)
NORM: 'std'
# Eval mode of patch selector (3xrandom, topk, multinomial)
SCORER_EVAL_MODE: 'multi'
SCORER_EVAL_USE_GRID: True

# For proximity loop closure 
LOOP_CLOSURE: False #True # False  #是否采用GBA
BACKEND_THRESH: 64.0
MAX_EDGE_AGE: 1000
GLOBAL_OPT_FREQ: 15 #每15帧进行一次全局优化

# For IMU integration
ENALBE_IMU: True #采用IMU
Ti1c: [0.9999, -0.0122,  0.0063, 0.0067,      
       0.0121,  0.9998,  0.0093, 0.0007,
      -0.0064, -0.0092,  0.9999, 0.0342,
       0.0,     0.0,     0.0,    1.0]
ENALBE_INV: False #若传入的为T_cam_imu，则设为True,做逆变换
accel_noise_sigma: 2.0000e-3
gyro_noise_sigma: 1.6968e-04
accel_bias_sigma: 3.0000e-3
gyro_bias_sigma: 1.9393e-05